version: '2'

services:
    server:
        build: .
        ports:
            - "3000:3000"
        volumes:
            - "~/.ssh:/root/.ssh"
            - "./server:/usr/src/app"
        environment:
            NODE_ENV: development
        # links:
        #     - "db"
        # depends_on:
        #     - "db"
        tty: true
        # command: ["nodemon", "-exec 'npm start'"]
    # db:
    #   image: mongo
